name: Build AmneziaWG for GL.iNet GL-MT6000

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERMAGIC_EXPECTED: "9469a6c8c449c47e503c05678ea1559d-r1"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip wget unzip

      - name: Clone GL.iNet Imagebuilder Repository
        run: |
          git clone https://github.com/gl-inet/imagebuilder.git
          cd imagebuilder
          make GL-MT6000

      - name: Setup .config
        run: |
          cd imagebuilder
          
          # Download standard config
          wget https://dl.gl-inet.com/firmware/mt6000/qsdk/24.10.0-rc5/config.buildinfo -O .config

          # Добавляем нужные пакеты
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-amneziawg=y" >> .config

          # Минимизируем сборку
          sed -i 's/CONFIG_TARGET_IMAGES_PAD=y/# CONFIG_TARGET_IMAGES_PAD is not set/' .config || true
          sed -i 's/CONFIG_TARGET_ROOTFS_INITRAMFS=y/# CONFIG_TARGET_ROOTFS_INITRAMFS is not set/' .config || true
          sed -i 's/CONFIG_TARGET_ROOTFS_SQUASHFS=y/# CONFIG_TARGET_ROOTFS_SQUASHFS is not set/' .config || true
          echo "# CONFIG_TARGET_BUILD_KERNEL is not set" >> .config

          make defconfig

      - name: Build
        run: |
          cd imagebuilder
          make -j$(nproc) V=s

          # Проверяем vermagic
          VERMAGIC=$(cat ./build_dir/target-*/linux-*/linux-*/.vermagic)
          echo "Detected vermagic: $VERMAGIC"
          if [ "$VERMAGIC" != "$VERMAGIC_EXPECTED" ]; then
            echo "Vermagic mismatch: $VERMAGIC, expected: $VERMAGIC_EXPECTED"
            exit 1
          fi

          # Собираем пакеты
          make package/kmod-amneziawg/{clean,download,prepare,compile} V=s
          make package/amneziawg-tools/{clean,download,prepare,compile} V=s
          make package/luci-app-amneziawg/{clean,download,prepare,compile} V=s

      - name: Collect Artifacts
        run: |
          mkdir -p awgrelease
          find imagebuilder/bin/packages/ -name "*amneziawg*.ipk" -exec cp {} awgrelease/ \;

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: awgrelease/*.ipk
