name: Build AmneziaWG for GL.iNet (Force Depends)
on:
  workflow_dispatch:
    push:
      tags:
        - "v*.*.*"

jobs:
  build:
    name: "Build with Forced Depends"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout OpenWrt
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v24.10.0-rc5
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses5-dev gawk git libssl-dev \
            gettext zlib1g-dev swig unzip time rsync python3 python3-setuptools

      - name: Setup feeds
        run: |
          echo "src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure minimal build
        run: |
          cat > .config <<EOF
          CONFIG_TARGET_mediatek=y
          CONFIG_TARGET_mediatek_filogic=y
          CONFIG_PACKAGE_kmod-amneziawg=m
          CONFIG_PACKAGE_amneziawg-tools=y
          EOF
          make defconfig

      - name: Build packages
        run: |
          make package/kmod-amneziawg/compile V=s
          make package/amneziawg-tools/compile V=s

      - name: Prepare install script
        run: |
          cat > install.sh <<'EOF'
          #!/bin/sh
          echo "Installing with forced dependencies..."
          opkg install --force-depends --force-checksum --force-overwrite kmod-amneziawg*.ipk
          opkg install amneziawg-tools*.ipk
          echo "Verifying installation:"
          lsmod | grep amnezia || echo "Module not loaded! Try rebooting."
          EOF
          chmod +x install.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: amnezia-packages
          path: |
            bin/targets/mediatek/filogic/packages/kmod-amneziawg_*.ipk
            bin/packages/*/awgopenwrt/amneziawg-tools_*.ipk
            install.sh
