name: Build AmneziaWG for GL.iNet GL-MT6000
on: 
  workflow_dispatch:
    push:
      tags:
        - "v*.*.*"

jobs:
  build:
    name: "OpenWrt Build for GL.iNet"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_env:
          - tag: "24.10.0-rc5"
            pkgarch: "aarch64_cortex-a53"
            target: "mediatek"
            subtarget: "filogic"
            vermagic: "9469a6c8c449c47e503c05678ea1559d-r1"

    steps:
      - name: Checkout OpenWrt
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v24.10.0-rc5
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses5-dev gawk git libssl-dev \
            gettext zlib1g-dev swig unzip time rsync python3 python3-setuptools \
            binutils file

      - name: Setup feeds
        run: |
          echo "src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build
        run: |
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/config.buildinfo -O .config
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-amneziawg=y" >> .config
          make defconfig CONFIG_TERMINAL=y2j NONINTERACTIVE=1

      - name: Build toolchain and kernel
        run: |
          make tools/install -j$(nproc)
          make toolchain/install -j$(nproc)
          make target/linux/{clean,prepare} V=s
          make target/linux/compile -j$(nproc) V=s

      - name: Build packages
        run: |
          make package/kmod-amneziawg/{clean,compile} V=s
          make package/luci-app-amneziawg/{clean,compile} V=s
          make package/amneziawg-tools/{clean,compile} V=s

      - name: Patch Vermagic in packages
        run: |
          sudo apt-get install -y binutils file
          find bin/ -name "kmod-amneziawg*.ipk" | while read pkg; do
            echo "Processing package: $pkg"
            
            TEMPDIR=$(mktemp -d)
            cp "$pkg" "$TEMPDIR/original.ipk"
            
            # Extract IPK
            (cd "$TEMPDIR" && ar x original.ipk) || {
              echo "Failed to extract ar archive"
              file "$TEMPDIR/original.ipk"
              exit 1
            }
            
            # Extract control
            mkdir "$TEMPDIR/control"
            tar -xzf "$TEMPDIR/control.tar.gz" -C "$TEMPDIR/control"
            
            # Patch control file
            sed -i 's/83c6d4e14f7353564d3cadaf38a15bef/9469a6c8c449c47e503c05678ea1559d-r1/g' "$TEMPDIR/control/control"
            
            # Repack control
            (cd "$TEMPDIR/control" && tar -czf ../control.tar.gz .)
            
            # Create new IPK
            (cd "$TEMPDIR" && ar cr new.ipk debian-binary control.tar.gz data.tar.gz)
            
            # Verify new package
            if ! ar t "$TEMPDIR/new.ipk" >/dev/null; then
              echo "Invalid package after rebuild"
              exit 1
            fi
            
            # Replace original
            mv "$TEMPDIR/new.ipk" "$pkg"
            
            # Cleanup
            rm -rf "$TEMPDIR"
            
            echo "Verification:"
            ar p "$pkg" control.tar.gz | tar -xzO ./control | grep vermagic
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl-inet-packages
          path: |
            bin/packages/${{ matrix.build_env.pkgarch }}/awgopenwrt/*.ipk
            bin/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/packages/kmod-amneziawg_*.ipk
          retention-days: 5
