name: Build AmneziaWG for GL.iNet GL-MT6000
on: 
  workflow_dispatch:
    push:
      tags:
        - "v*.*.*"

jobs:
  build:
    name: "OpenWrt Build for GL.iNet"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_env:
          - tag: "24.10.0-rc5"
            pkgarch: "aarch64_cortex-a53"
            target: "mediatek"
            subtarget: "filogic"
            vermagic: "9469a6c8c449c47e503c05678ea1559d-r1"

    steps:
      - name: Checkout OpenWrt
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v24.10.0-rc5
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses5-dev gawk git libssl-dev \
            gettext zlib1g-dev swig unzip time rsync python3 python3-setuptools

      - name: Patch Vermagic before build
        run: |
          # Создаем файл с нужным vermagic
          echo "9469a6c8c449c47e503c05678ea1559d-r1" > vermagic.force
          
          # Находим и заменяем все vermagic.h
          find . -name vermagic.h | while read file; do
            echo "Patching $file"
            cp vermagic.force "$file"
          done

      - name: Setup feeds
        run: |
          echo "src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build
        run: |
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/config.buildinfo -O .config
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-amneziawg=y" >> .config
          make defconfig CONFIG_TERMINAL=y2j NONINTERACTIVE=1

      - name: Build toolchain and kernel
        run: |
          make tools/install -j$(nproc)
          make toolchain/install -j$(nproc)
          make target/linux/{clean,prepare} V=s
          make target/linux/compile -j$(nproc) V=s
          
          # Проверяем vermagic после сборки
          VERMAGIC=$(cat ./build_dir/target-*/linux-*/linux-*/.vermagic)
          echo "Resulting Vermagic: $VERMAGIC"
          if [ "$VERMAGIC" != "${{ matrix.build_env.vermagic }}" ]; then
            echo "Vermagic mismatch detected!"
            exit 1
          fi

      - name: Build packages
        run: |
          make package/kmod-amneziawg/{clean,compile} V=s
          make package/luci-app-amneziawg/{clean,compile} V=s
          make package/amneziawg-tools/{clean,compile} V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl-inet-packages
          path: |
            bin/packages/${{ matrix.build_env.pkgarch }}/awgopenwrt/*.ipk
            bin/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/packages/kmod-amneziawg_*.ipk
      
